### ISSUE TITLE
Issue on iPod 5

### ISSUE THREAD

**Issue by AssyriaGameStudio** [dkhamsing/DKScrollingTabController#13]
Slightly odd bug... It works great on my iPhone 6s, but when I run the same project on an iPod 5 (both running 9.3.2) the tab controller doesn't appear to accept any input, nor is it scrollable?

**Comment by dkhamsing** [comment]
Hmm yeah, will have to check it out

**Comment by ReadmeCritic** [comment]
Did you mean iPhone 5? Please share some code so I can review this
Thx

**Comment by ReadmeCritic** [comment]
Did you mean iPhone 5? Please share some code so I can review this
Thx

**Comment by bkcan** [comment]
I'm having the same problem but with all devices... I think the culprit is a UINavigationController?

I'm using it in two different view controllers. One that's connected to a UINavigationController and another that isn't. The one that is NOT connected to the UINavigationController works 100%. BUT when a view controller is connected, it shows the buttons but the view is unresponsive (i.e. can't scroll, can't press, doesn't show correct background color). This could be a whole other issue though...

**Comment by dkhamsing** [comment]
hm can u share some code or an example project
thanks

**Comment by bkcan** [comment]
It's the same implementation example code you provide. Just add that view controller as the root vc for a navigation controller with a nav bar through storyboard.

**Comment by bkcan** [comment]
Any suggestions or progress? I ran out of ideas of how to go around this bug.

**Comment by dkhamsing** [comment]
Hm sounds like you are not setting this up correctly

Can you use the code in the demo ?

**Comment by bkcan** [comment]
You're code in the demo works. It doesn't work when I connect a UINavigationController to the view controller that is using your code.

**Comment by dkhamsing** [comment]
@bkcan within a UINavigationController, the position set manually do not work

For the example `ViewControllerSimple`, if you replace 

>        tabController.view.frame = CGRectMake(0, 20, 320, 40);

by 

>        tabController.view.frame = CGRectMake(0, 60, 320, 40);

^ note the **60**

It should appear
